### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by mmubarak0** [mmubarak0/quizzat#1]
## Description

Implement a robust user authentication system for the backend.
This feature should include:

* **User Registration**: 
  * Allow new users to create an account with an `email` and `password`.
  * Implement an endpoint for user registration
* **User Login**: 
  * Enable existing users to log in using their credentials.
  * The proper method to access protected routes is by supplying the Authorization Header in the format: `Authorization: Bearer <token>`.
  * Create an endpoint for user login
* **Password Encryption**: 
  * Ensure all passwords are securely encrypted before storing them in the database.
* **Session Management**: 
  * Implement session handling to keep users logged in across different pages.
  * Set up a refresh token endpoint
* **Error Handling**: 
  * Provide clear error messages for failed login attempts and other authentication issues.
* **Testing**:
  * Write unit tests for each authentication component (registration, login, password handling, etc.).
  * Test edge cases (e.g., invalid credentials, expired sessions).
  * Verify that error messages are accurate and informative.

## Endpoints

| Method | Route |
|--------|--------|
| POST | `/api/v1/auth/register` |
| POST | `/api/v1/auth/login` |
| POST | `/api/v1/auth/refresh` |
| POST | `/api/v1/auth/password-reset` |
| POST | `/api/v1/auth/login?type=OAuth2&provider=Google` |

#### /register

```javascript
// valid response
{
  message: [ "success" ],
  statusCode: 201,
  accessToken: as234xc...,
  refreshToken: as234xc...,
  data: {
    _id: string,
    firstName: string,
    lastName: string,
    password: hashed string,
    createdAt: date,
    updatedAt: date,
  }
}

// invalid response
{
  message: [ "string" ],
  statusCode: number
}
// 422 for field validations and duplicate emails
// 500 internal server error
``` 

#### /login

```javascript
// valid response
{
  message: [ "success" ],
  statusCode: 200,
  accessToken: as234xc...,
  refreshToken: as234xc...
}

// invalid response
{
  message: [ "string" ],
  statusCode: number
}
// 404 user not found
// 422 for field validations and wrong email/password
// 500 internal server error
``` 

#### /refresh

```javascript
{
  message: [ "refresh token updated" ],
  statusCode: 200,
  refreshToken: as234xc...
}

// invalid response
{
  message: [ "string" ],
  statusCode: number
}
// 404 user not found
// 401 unauthorized access / invalid token
// 401 for field validations / missing token
// 500 internal server error
``` 

#### /password-reset

```javascript
{
  message: [ "success" ],
  statusCode: 200
}
``` 

## Tasks:

- [ ] Set up user registration endpoint.
- [ ] Create user login endpoint.
- [ ] Implement password encryption.
- [ ] Develop session management.
- [ ] Add error handling for authentication processes.

## Testing

- [ ] Write unit tests for registration
- [ ] Write unit tests for login
- [ ] Test edge cases missing input
- [ ] Verify that error messages are accurate and informative.
